<div class="border rounded p-3 mb-3" data-channel-row>
  <input type="hidden" name="channels[{{ $i }}][id]" value="{{ $channel['id'] ?? '' }}">
  <div class="row">
    <div class="col-md-3 form-group"><label>Etiqueta</label><input class="form-control" name="channels[{{ $i }}][label]" value="{{ $channel['label'] ?? '' }}" placeholder="Ej.: FM 98.7"></div>
    <div class="col-md-2 form-group"><label>Tipo</label><select class="form-control" name="channels[{{ $i }}][channel_type]"><option value="">Seleccionar</option>@foreach(['frequency'=>'Frecuencia','stream'=>'Stream','website'=>'Sitio web','platform'=>'Plataforma'] as $value => $label)<option value="{{ $value }}" @selected(($channel['channel_type'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-md-2 form-group"><label>Plataforma</label><select class="form-control" name="channels[{{ $i }}][platform]"><option value="">No aplica</option>@foreach(['sitio_web','stream_directo','youtube','facebook','twitch','tunein','radio_garden','spotify','otra_oficial'] as $platform)<option value="{{ $platform }}" @selected(($channel['platform'] ?? '') === $platform)>{{ ucfirst(str_replace('_', ' ', $platform)) }}</option>@endforeach</select></div>
    <div class="col-md-2 form-group"><label>Banda</label><select class="form-control" name="channels[{{ $i }}][frequency_band]"><option value="">-</option><option value="AM" @selected(($channel['frequency_band'] ?? '') === 'AM')>AM</option><option value="FM" @selected(($channel['frequency_band'] ?? '') === 'FM')>FM</option></select></div>
    <div class="col-md-3 form-group"><label>Frecuencia</label><input class="form-control" name="channels[{{ $i }}][frequency]" value="{{ $channel['frequency'] ?? '' }}" placeholder="Ej.: 98.7"></div>
    <div class="col-md-8 form-group"><label>URL oficial</label><input class="form-control" type="url" name="channels[{{ $i }}][url]" value="{{ $channel['url'] ?? '' }}"></div>
    <div class="col-md-4 form-group d-flex align-items-end justify-content-between"><div><input type="hidden" name="channels[{{ $i }}][is_primary]" value="0"><label class="mr-3"><input type="checkbox" data-primary-channel name="channels[{{ $i }}][is_primary]" value="1" @checked((bool) ($channel['is_primary'] ?? false))> Principal</label><input type="hidden" name="channels[{{ $i }}][is_active]" value="0"><label><input type="checkbox" name="channels[{{ $i }}][is_active]" value="1" @checked((bool) ($channel['is_active'] ?? true))> Activo</label></div><button class="btn btn-outline-danger btn-sm" type="button" data-remove-channel>Quitar</button></div>
  </div>
</div>
