@extends('adminlte::page')

@section('title', 'Radios')
@section('content_header')<h1>Señales de radio</h1>@stop
@section('content')
<div class="card card-outline card-primary shadow-sm"><div class="card-header"><h3 class="card-title">Directorio evergreen</h3><div class="card-tools"><a class="btn btn-success btn-sm" href="{{ route('backend.radios.signals.create') }}">Crear señal</a></div></div><div class="card-body">
<form class="row mb-3" method="GET"><div class="col-md-3 mb-2"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Buscar señal"></div><div class="col-md-2 mb-2"><select class="form-control" name="status"><option value="">Estado</option>@foreach(['draft','approved','published','archived'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select></div><div class="col-md-3 mb-2"><select class="form-control select2" name="province_id"><option value="">Provincia</option>@foreach($provincias as $province)<option value="{{ $province->id }}" @selected((int) request('province_id') === $province->id)>{{ $province->nombre }}</option>@endforeach</select></div><div class="col-md-2 mb-2"><select class="form-control" name="mode"><option value="">Emisión</option>@foreach(['air'=>'Aire','web'=>'Web','streaming'=>'Streaming'] as $value=>$label)<option value="{{ $value }}" @selected(request('mode') === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2 mb-2"><button class="btn btn-primary">Filtrar</button> <a class="btn btn-default" href="{{ route('backend.radios.signals.index') }}">Limpiar</a></div></form>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Señal</th><th>Territorio</th><th>Emisión</th><th>Estado</th><th>Programas</th><th></th></tr></thead><tbody>@forelse($signals as $signal)<tr><td>{{ $signal->title }}</td><td>{{ $signal->provincia?->nombre ?? '-' }}{{ $signal->city ? ' · '.$signal->city : '' }}</td><td>{{ implode(', ', $signal->transmission_modes ?? []) }}</td><td>{{ $signal->editorial_status }}</td><td>{{ $signal->programs_count }}</td><td class="text-right"><a class="btn btn-warning btn-sm" href="{{ route('backend.radios.signals.edit',$signal) }}">Editar</a>@if($signal->editorial_status !== 'published')<form class="d-inline" method="POST" action="{{ route('backend.radios.signals.publish',$signal) }}">@csrf<button class="btn btn-success btn-sm">Publicar</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">No hay señales para los filtros seleccionados.</td></tr>@endforelse</tbody></table></div>{{ $signals->links() }}</div></div>
@stop
