<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\StoreNewsRequest;
use App\Http\Requests\Api\UpdateNewsRequest;
use App\Models\Noticia;
use Illuminate\Http\Request;

class NewsController extends Controller
{
  /**
   * Display a listing of the resource.
   */
  public function index(Request $request)
  {
    $query = Noticia::query();

    // Optional filtering can be added here
    if ($request->has('categoria_id')) {
      $query->where('categoria_id', $request->query('categoria_id'));
    }

    if ($request->has('estado')) {
      $query->where('estado', $request->query('estado'));
    }

    $news = $query->latest()->paginate(15);

    return response()->json($news);
  }

  /**
   * Store a newly created resource in storage.
   */
  public function store(StoreNewsRequest $request)
  {
    $validated = $request->validated();

    // Handle slug creation if not provided or auto-generated by model events
    if (!isset($validated['slug']) && isset($validated['titulo'])) {
      $validated['slug'] = \Illuminate\Support\Str::slug($validated['titulo']);
    }

    $news = Noticia::create($validated);

    return response()->json($news, 201);
  }

  /**
   * Display the specified resource.
   */
  public function show(Noticia $news)
  {
    return response()->json($news);
  }

  /**
   * Update the specified resource in storage.
   */
  public function update(UpdateNewsRequest $request, Noticia $news)
  {
    $validated = $request->validated();

    // Update slug if title changes, optional
    if (isset($validated['titulo']) && !isset($validated['slug'])) {
      $validated['slug'] = \Illuminate\Support\Str::slug($validated['titulo']);
    }

    $news->update($validated);

    return response()->json($news);
  }

  /**
   * Remove the specified resource from storage.
   */
  public function destroy(Noticia $news)
  {
    $news->delete();

    return response()->json(null, 204);
  }
}
