
services:

  app:
    build: ./
    environment:
      VIRTUAL_HOST: mfa.local
      VIRTUAL_PORT: 80
    working_dir: /var/www/html
    image: mfa_app
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    networks:
      - app-network
      - shared-web

  db:
    image: mariadb:10.8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mfa
      MYSQL_ROOT_PASSWORD: mfa
      MYSQL_PASSWORD: mfa
      MYSQL_USER: mfa
    volumes:
      - lmfa_db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.1.1
    environment:
      PMA_HOST: db
      PMA_USER: mfa
      PMA_PASSWORD: mfa
      UPLOAD_LIMIT: 64M
      VIRTUAL_HOST: pma.mfa.local
    networks:
      - app-network
      - shared-web
    depends_on:
      - db

networks:
  app-network:
  shared-web:
    external: true

volumes:
  lmfa_db_data:
